### ISSUE TITLE
How does this work without a MAR server

### ISSUE THREAD

**Issue by syloktools** [mohlcyber/MISP-MVISION-EDR#3]
We are new customers to EDR and we did not have MAR. How does this work if you do not have the MAR topic in DXL authorizations?

**Comment by mohlcyber** [comment]
Hi Robert, great point. Let me publish another version that is using the API's and not DXL. Give me a few days and will provide you with an update here.

**Comment by mohlcyber** [comment]
Hi Robert, just finished to write another script using the API. Can be found in the same repo.
https://github.com/mohlcyber/MISP-MVISION-EDR/blob/master/misp_edr.py

Let me know how it goes. I will close the issue for now. Please reopen if you have any questions.
All the best,
Martin
